## Para que todos trabajemos en el mismo archivo
## PROYECTO FINAL - VISION ARTIFICIAL 2020-1- UNDERSTANDING THE AMAZON FROM SPACE
#--------- JESSICA CASTILLO, JUAN DAVID GARCIA, JUAN FRANCISCO SUESCUN-------------#

